image: python:3.9.4

variables:
  notebook_folder: "/notebook_store/"
  cluster_id: ""
  DATABRICKS_TOKEN: ""
  DATABRICKS_HOST: ""

before_script:
  - chmod +x ./ci/*.sh
  - apt-get update && apt-get install jq -y
  - pip install databricks-cli==0.16.5

stages:
  - Starting_cluster
  - Importing_motebooks_and_data
  - Running_notebooks

Starting_cluster:
  stage: Starting_cluster
  script:
    - ./ci/start_cls.sh

Importing_motebooks_and_data:
  stage: Importing_motebooks_and_data
  script:
    - databricks workspace import variational_autoencoder_spark.ipynb ${notebook_folder} -o

Running_notebooks:
  stage: Running_notebooks
  script:
    - export notebook_name=variational_autoencoder_spark
    - echo "Running Notebook ${notebook_name}"
    - ./ci/runNotebook.sh